# Site settings
url: http://opengapps.org
title: The Open GApps Project
description: OpenGApps.org offers information and pre-built packages of The Open GApps Project. The Open GApps Project is an open-source effort to script the automatic generation of up-to-date Google Apps packages. All Android versions and platforms supported.
keywords: open gapps, opengapps, gapps, android, daily, arm, arm64, x86, x86_64, 4.4, 5.0, 5.1, 6.0, aroma
timezone: Europe/Amsterdam

# Libraries
gfont: https://fonts.googleapis.com
mdl: https://storage.googleapis.com/code.getmdl.io/1.1.3
pushbullet: https://www.pushbullet.com/channel-popup?tag=
ads: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

# Variables/Resouces
ga: Google Apps
org: OpenGApps.org
img: /images/
apimg: /images/apple-icon-
animg: \/images\/android-icon-
color: '#009688'

# Blog
blogurl: /blog
blogimg: /blog/images/
paginate: 5
paginate_path: /blog/page/:num
permalink: /blog/post/:year/:month/:day/:title/
disqus: opengapps.disqus.com

# Gems
gems: [jekyll-paginate]

# Support
support:
 faq: https://github.com/opengapps/opengapps/wiki/FAQ
 wiki: https://github.com/opengapps/opengapps/wiki
 xdaqa: http://forum.xda-developers.com/showthread.php?t=3124506
 xdadev: http://forum.xda-developers.com/android/software/Open-GApps-t3098071
 gitter: https://gitter.im/opengapps/general

# SASS
sass:
 style: compressed
